<?php

namespace SMiami\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnuncioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnuncioRepository extends EntityRepository
{
    public function getDamas()
    {
        $em = $this->getEntityManager();
        
        $strSQL = "SELECT a.id, a.nombre, co.nombre AS condado, ci.nombre AS ciudad, i.path AS imagen FROM SiteBundle:Anuncio a JOIN a.condado co JOIN a.ciudad ci JOIN a.imagenes i WHERE i.portada = true";
        $consulta = $em->createQuery($strSQL);
        
        return $consulta->getResult();
    }
}
