<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 * 
 * @ORM\Entity()
 */
class User extends BaseUser
{
    /**
    * @var integer $id
    *
    * @ORM\Id
    * @ORM\Column(type="integer")
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    protected $id;
    
    /**
    *
    * @var ArrayCollection
    *
    */
    private $anuncios;
    
    

    /**
    * Constructor
    */
    public function __construct()
    {
        parent::__construct();
        $this->anuncios = new \Doctrine\Common\Collections\ArrayCollection();
    }
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
    * Add anuncio
    *
    * @param \SMiami\SiteBundle\Entity\Anuncio $anuncios
    * @return User
    */
    public function addAnuncio(\SMiami\SiteBundle\Entity\Anuncio $anuncios)
    {
        $this->anuncios[] = $anuncios;
    
        return $this;
    }

    /**
    * Remove anuncio
    *
    * @param \Inass\HelpdeskBundle\Entity\Incidencia $incidencias
    */
    public function removeAnuncio(\SMiami\SiteBundle\Entity\Anuncio $anuncios)
    {
        $this->anuncios->removeElement($anuncios);
    }

    /**
    * Get anuncios
    *
    * @return \Doctrine\Common\Collections\Collection
    */
    public function getAnuncios()
    {
        return $this->anuncios;
    }
}